<a href="https://colab.research.google.com/github/divyamjariwal/Deep-Learning-Lab/blob/main/DL_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [19]:
import torch
import numpy as np


Creating 1D, 2D, and 3D Tensors

In [20]:
# 1D NumPy array
np_1d = np.array([1, 2, 3])

# 2D NumPy array
np_2d = np.array([[1, 2],
                  [3, 4]])

# 3D NumPy array
np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(np_1d)
print(np_2d)
print(np_3d)


[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Using PyTorch

In [21]:
# 1D tensor
t_1d = torch.tensor([1, 2, 3])

# 2D tensor
t_2d = torch.tensor([[1, 2],
                     [3, 4]])

# 3D tensor
t_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(t_1d)
print(t_2d)
print(t_3d)


tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Basic Element-Wise Operations

In [22]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 5, 6])

# Element-wise operations
print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division


tensor([12, 25, 36])
tensor([ 8, 15, 24])
tensor([ 20, 100, 180])
tensor([5., 4., 5.])


Dot Product (1D tensors)

In [23]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Dot product
dot_product = torch.dot(x, y)
print(dot_product)


tensor(32)


Matrix Multiplication (2D tensors)

In [24]:
m1 = torch.tensor([[1, 2],
                   [3, 4]])

m2 = torch.tensor([[5, 6],
                   [7, 8]])

# Matrix multiplication
result = torch.matmul(m1, m2)
print(result)


tensor([[19, 22],
        [43, 50]])


Indexing & Slicing

In [25]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0])        # First row
print(t[:, 1])     # Second column
print(t[1, 2])     # Specific element


tensor([10, 20, 30])
tensor([20, 50])
tensor(60)


Boolean Masking

In [26]:
data = torch.tensor([5, 10, 15, 20, 25])

# Mask values greater than 15
mask = data > 15
print(mask)
print(data[mask])


tensor([False, False, False,  True,  True])
tensor([20, 25])


Extracting Sub-Tensors

In [27]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Extract middle 2x2 matrix
sub_tensor = matrix[0:2, 1:3]
print(sub_tensor)


tensor([[2, 3],
        [5, 6]])


Shape Manipulation in PyTorch

In [28]:
t = torch.tensor([1, 2, 3, 4, 5, 6])


In [29]:
print(t.view(2, 3))


tensor([[1, 2, 3],
        [4, 5, 6]])


In [30]:
print(t.reshape(3, 2))


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [31]:
t_unsq = t.unsqueeze(0)   # Adds dimension at index 0
print(t_unsq.shape)


torch.Size([1, 6])


In [32]:
t_sq = t_unsq.squeeze()
print(t_sq.shape)


torch.Size([6])


NumPy .reshape() Comparison

In [33]:
np_arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape NumPy array
np_reshaped = np_arr.reshape(2, 3)
print(np_reshaped)


[[1 2 3]
 [4 5 6]]


Broadcasting (Different Shapes)

In [34]:
# Tensor with shape (3, 3)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Tensor with shape (3,)
B = torch.tensor([10, 20, 30])

# Broadcasting happens automatically
print(A + B)


tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39]])


In-Place vs Out-of-Place Operations

In [35]:
x = torch.tensor([1, 2, 3])
y = x + 5

print(x)  # Original unchanged
print(y)


tensor([1, 2, 3])
tensor([6, 7, 8])


In [36]:
x = torch.tensor([1, 2, 3])

x.add_(5)  # In-place operation (underscore _)
print(x)


tensor([6, 7, 8])
